# Generated by Django 2.2.7 on 2020-10-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SlugField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('born_date', models.DateField()),
                ('parents', models.TextField()),
                ('breeder_or_kennel', models.CharField(max_length=200, null=True)),
                ('titles', models.TextField(null=True)),
                ('working_titles', models.TextField(null=True)),
                ('tests', models.TextField(null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='dogs')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ImageField(blank=True, null=True, upload_to='dogs/gallery')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='Engine.Dog')),
            ],
        ),
    ]
